# -*- coding: utf-8 -*-
"""FuzzyIdade.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-rsri1V9m2rdzNx-YlyP5xoMsbn_cMWG
"""

import numpy as np
import matplotlib.pyplot as plt

def gauss(x, c, sigma):
    return np.exp(-0.5 * ((x - c) / sigma) ** 2)

def sigmoide(x, c, sigma):
    return 1 / (1 + np.exp(-(x - c) / sigma))

# Intervalo
x = np.linspace(0, 90, 2000)

# Conjuntos fuzzy
jovem = 1 - sigmoide(x, 25, 4)
adulto = gauss(x, 40, 10)
idoso  = sigmoide(x, 55, 4)

# Entrada
idade = float(input("Digite a sua idade (0 a 90): "))

j = 1 - sigmoide(idade, 25, 4)
a = gauss(idade, 40, 10)
i = sigmoide(idade, 55, 4)

# Grupo com maior pertinência
valores = {"Jovem": j, "Adulto": a, "Idoso": i}
grupo = max(valores, key=valores.get)

print(f"Idade: {idade} anos")
print(f"Jovem: {j:.2f}")
print(f"Adulto: {a:.2f}")
print(f"Idoso: {i:.2f}")
print(f"Grupo com maior pertinência: {grupo}")

# Plotagem
plt.figure(figsize=(10,6))
plt.plot(x, jovem, label="Jovem", color="#1f77b4", linewidth=2.5, alpha=0.8)
plt.plot(x, adulto, label="Adulto", color="#ff7f0e", linewidth=2.5, alpha=0.8)
plt.plot(x, idoso, label="Idoso", color="#2ca02c", linewidth=2.5, alpha=0.8)

# Marcar idade
plt.axvline(idade, linestyle="--", color="gray", linewidth=1.2, alpha=0.7)
plt.scatter([idade], [j], color="#1f77b4", s=90, edgecolors="black")
plt.scatter([idade], [a], color="#ff7f0e", s=90, edgecolors="black")
plt.scatter([idade], [i], color="#2ca02c", s=90, edgecolors="black")

plt.title("Partição Fuzzy de Idade", fontsize=16, weight="bold")
plt.xlabel("Idade (anos)", fontsize=12)
plt.ylabel("Grau de pertinência", fontsize=12)
plt.ylim(-0.05, 1.05)
plt.grid(alpha=0.3, linestyle="--")
plt.legend(fontsize=11)
plt.show()